### PR TITLE
Linking to repositories and contributors' profiles

### PR DESCRIPTION
**Pull request by PatMyron**

### CODE REVIEW

**Comment by haacked** [comment]
Good idea!

**Comment by PatMyron** [comment]
@Haacked ah, looks like the markdown links didn't render for some reason: https://haacked.github.io/gh-pages-demo/

Is there any way to test the rendering locally? I'll look into it if so

**Comment by PatMyron** [comment]
Looks like https://github.com/Haacked/gh-pages-demo/commit/c3a5ce74e015c511714668fe7121b809affdf5ac and https://github.com/Haacked/gh-pages-demo/commit/0df5fa1b3d1f4322851d392e0ad021ebca3dfac0 fixed it. Cool, thanks!

**Comment by haacked** [comment]
Thanks for your contributions! It's nice to have the demo actually show another contributor now. :smile:

**Pull request merged**
