### PR TITLE
Added "style"

### PR DESCRIPTION
**Pull request by TehShrike**
- added style.css
- centered content div, gave it a set width

### CODE REVIEW

**Comment by TehShrike** [comment]
Bump :-)

**Comment by TehShrike** [comment]
This is one of my oldest still-relevant pull requests!

**Comment by TehShrike** [comment]
😢

**Comment by haacked** [comment]
So sorry! I wasn't watching notifications on this repo. I ended up using GitHub's theme functionality. Check out this PR to see how much config has been simplified! https://github.com/Haacked/gh-pages-demo/pull/5

**Comment by TehShrike** [comment]
😅

**Pull request closed without merging**
